mod "main";

type Person {
    x: int;
    l: bool;
    p: User;
}

type User {
    order: int;
}

fn call_me(x: int, person: Person) -> Person {
    let person:Person = {
        x: 2,
        l: false,
        p: {
            order: 10,
        },
    };
    return person;
}

fn hello(x: int, user: User) -> int {
    let x:int = 10;
    for (x > 0) {
        let y:User;
    }
    let p: Person = {
      x: 2, 
      l: false, 
      p: {
        order: 43, 
      },
    };
    call_me(23, p);
    p = call_me(23, p);
    return x;
} 
